apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-redis
data:
  REDIS_HOST: {{ .Values.redis.host }}
  REDIS_PORT: {{ .Values.redis.port }}
  REDIS_USERNAME: {{ .Values.redis.username }}
  REDIS_PASSWORD: {{ .Values.redis.password }}
  REDIS_DATABASE: {{ .Values.redis.database }}
  REDIS_TLS: {{ .Values.redis.tls }}